sign-commit = true
sign-tag = true
tag-message = "Release version {{version}}"
push = true
publish = true

pre-release-replacements = [
  {file="README.md", search="tokio-prometheus-metered=channel = .*", replace="tokio-prometheus-metered-channel = \"{{version}}\""},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
]
